// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestmedicoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void testmedico() {
    driver.get("http://localhost/login_medicos");
    driver.manage().window().setSize(new Dimension(1936, 1056));
    driver.findElement(By.id("crm")).click();
    driver.findElement(By.id("crm")).sendKeys("111");
    driver.findElement(By.id("senha")).click();
    driver.findElement(By.id("senha")).sendKeys("111111");
    driver.findElement(By.id("senha")).sendKeys(Keys.ENTER);
    driver.findElement(By.cssSelector("#dashboard > .title")).click();
    driver.findElement(By.cssSelector("#solicitar-exame > .title")).click();
    driver.findElement(By.cssSelector("#prontuario > .title")).click();
    driver.findElement(By.cssSelector("#solicitar-exame > .title")).click();
    driver.findElement(By.id("cpf")).click();
    driver.findElement(By.id("cpf")).sendKeys("123123123");
    driver.findElement(By.id("data")).click();
    driver.findElement(By.id("data")).click();
    driver.findElement(By.id("data")).sendKeys("2021-04-27");
    driver.findElement(By.id("data")).click();
    driver.findElement(By.cssSelector(".item-cadastro-tipo-exame")).click();
    driver.findElement(By.name("TipoExame")).click();
    {
      WebElement dropdown = driver.findElement(By.name("TipoExame"));
      dropdown.findElement(By.xpath("//option[. = 'Ecocardiograma']")).click();
    }
    driver.findElement(By.cssSelector("option:nth-child(2)")).click();
    driver.findElement(By.cssSelector("#dashboard > .title")).click();
    driver.findElement(By.id("2")).click();
    driver.findElement(By.id("2")).click();
    driver.findElement(By.id("3")).click();
    driver.close();
  }
}
